CREATE TABLE jogos(
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	descricao VARCHAR(10000) NOT NULL,
	preco  DECIMAL(20,2) NOT NULL,
	desenvolvedora VARCHAR(255) NOT NULL,
	imagemurl VARCHAR(255) NOT NULL
);